import React,{useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import{AreaChart,Area,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid,LineChart,Line,BarChart,Bar}from"recharts";
import{Activity,AlertTriangle,ArrowRight,BrainCircuit,CloudRain,Droplets,FlaskConical,Globe2,Leaf,Map,Menu,Microscope,Satellite,Sprout,Sun,Thermometer,UploadCloud,Wind,X,Zap,CheckCircle2,Database,ShieldCheck}from"lucide-react";
import"./styles.css";

const nav=[["home","Home",Leaf],["dashboard","Smart Farm",Activity],["doctor","AI Crop Doctor",BrainCircuit],["irrigation","Irrigation",Droplets],["risk","15-Day Risk",AlertTriangle],["weather","Weather",CloudRain],["crops","Crop Recommender",Sprout],["soil","Soil",FlaskConical],["map","Farm Map",Map],["analytics","Analytics",Microscope],["impact","Impact",Zap],["method","How It Works",Globe2]];
const moisture=[{x:"06",m:51,t:27},{x:"09",m:49,t:29},{x:"12",m:45,t:31},{x:"15",m:42,t:32},{x:"18",m:44,t:30},{x:"21",m:47,t:28}];
const risks=[{x:"Today",heat:24,water:32,rain:18,disease:28},{x:"+3d",heat:38,water:41,rain:26,disease:35},{x:"+6d",heat:46,water:49,rain:44,disease:48},{x:"+9d",heat:52,water:57,rain:61,disease:55},{x:"+12d",heat:44,water:62,rain:69,disease:63},{x:"+15d",heat:39,water:55,rain:48,disease:51}];

function App(){
 const[tab,setTab]=useState("home"),[menu,setMenu]=useState(false),[bn,setBn]=useState(false),[mode,setMode]=useState("farmer");
 const go=id=>{setTab(id);setMenu(false);scrollTo({top:0,behavior:"smooth"})};
 return <><header><div className="brand" onClick={()=>go("home")}><span className="brandIcon"><Leaf/></span><div><b>AgriNova</b><small>Smart Agriculture</small></div></div><nav>{nav.slice(0,7).map(([id,n,I])=><button className={tab===id?"sel":""} onClick={()=>go(id)} key={id}><I/> {n}</button>)}</nav><div className="actions"><button onClick={()=>setMode(mode==="farmer"?"researcher":"farmer")} className="pill">{mode==="farmer"?"Farmer":"Researcher"} Mode</button><button className="pill" onClick={()=>setBn(!bn)}>{bn?"EN":"বাংলা"}</button><button className="hamb" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>{menu&&<div className="mobileMenu">{nav.map(([id,n,I])=><button onClick={()=>go(id)} key={id}><I/>{n}</button>)}</div>}<main>
 {tab==="home"&&<Home go={go}/>} {tab==="dashboard"&&<Dashboard/>} {tab==="doctor"&&<Doctor/>} {tab==="irrigation"&&<Irrigation/>} {tab==="risk"&&<Risk/>} {tab==="weather"&&<Weather/>} {tab==="crops"&&<Crops/>} {tab==="soil"&&<Soil/>} {tab==="map"&&<FarmMap/>} {tab==="analytics"&&<Analytics/>} {tab==="impact"&&<Impact/>} {tab==="method"&&<Method/>}
 </main><footer><b>AgriNova</b><span>Built for Bangladesh. Designed for the World.</span><small>Demo / Simulation Data · Verified sources required for production deployment.</small></footer></>
}
function Shell({ey,title,desc,children}){return <section className="page"><div className="ey">{ey}</div><h1>{title}</h1><p className="lead">{desc}</p>{children}</section>}
function Home({go}){return <><section className="hero"><div><div className="ey"><i/>AI + IoT + Weather + Soil Intelligence</div><h1>Every Drop.<br/>Every Crop.<br/><em>Every Decision — Smarter.</em></h1><p>One decision-support system for monitoring farm conditions, understanding risk and turning data into practical action.</p><div className="heroBtns"><button className="primary" onClick={()=>go("dashboard")}>Open Smart Farm Dashboard <ArrowRight/></button><button className="secondary" onClick={()=>go("method")}>Explore How It Works</button></div><div className="proof"><span>✓ Simulation clearly labelled</span><span>✓ Explainable decisions</span><span>✓ Built for scale</span></div></div><div className="heroArt"><div className="orb orb1"/><div className="orb orb2"/><div className="plant"><Sprout/></div><div className="float a"><Droplets/><b>48.2%</b><small>soil moisture</small></div><div className="float b"><CloudRain/><b>32%</b><small>rain probability</small></div><div className="float c"><ShieldCheck/><b>Low</b><small>current risk</small></div></div></section><section className="stats">{[["87/100","Farm health","Illustrative"],["48.2%","Soil moisture","Simulation"],["72h","Weather horizon","Demo feed"],["15 days","Risk outlook","Model interface"]].map(x=><div key={x[1]}><b>{x[0]}</b><strong>{x[1]}</strong><small>{x[2]}</small></div>)}</section><div className="featureGrid"><Feature I={BrainCircuit} t="AI Crop Doctor" d="Symptoms + image + environment → explainable crop diagnosis workflow." go={()=>go("doctor")}/><Feature I={Droplets} t="Smart Irrigation" d="Use moisture and forecast signals to decide when irrigation should trigger." go={()=>go("irrigation")}/><Feature I={AlertTriangle} t="15-Day Risk" d="See heat, water, rainfall and disease risk as uncertainty-aware signals." go={()=>go("risk")}/></div></>}
function Feature({I,t,d,go}){return <button className="feature" onClick={go}><span className="ficon"><I/></span><h3>{t}</h3><p>{d}</p><ArrowRight/></button>}
function Dashboard(){return <Shell ey="LIVE FARM VIEW · DEMO" title="Smart Farm Dashboard" desc="Environmental signals, soil status and decision priorities in one view. Values are simulation data."><div className="metricGrid">{[["28.5°C","Temperature","26–32°C",Thermometer],["48.2%","Soil moisture","40–60%",Droplets],["pH 6.4","Soil pH","5.8–7.0",FlaskConical],["32%","Rain probability","Next 24h",CloudRain]].map(([v,n,r,I])=><div className="metric" key={n}><I/><b>{v}</b><strong>{n}</strong><small>Ideal: {r}</small><em>Updated 4 min ago</em></div>)}</div><div className="two"><div className="panel"><Head t="Moisture & temperature" s="Last 24h · simulated"/><ResponsiveContainer width="100%" height={290}><AreaChart data={moisture}><CartesianGrid vertical={false} opacity=".2"/><XAxis dataKey="x"/><YAxis/><Tooltip/><Area dataKey="m" type="monotone" stroke="var(--green)" fill="none" strokeWidth={3}/><Line dataKey="t" stroke="#24362f" strokeWidth={2}/></AreaChart></ResponsiveContainer></div><div className="panel center"><Head t="Farm Health" s="Illustrative"/><div className="health"><b>87</b><span>/100</span></div><p>Illustrative formula: 30% moisture + 25% temperature + 20% pH + 15% weather + 10% crop signals.</p><div className="miniBars"><i style={{width:"86%"}}>Moisture</i><i style={{width:"91%"}}>Temperature</i><i style={{width:"82%"}}>Soil</i></div></div></div><div className="panel"><Head t="Today's decision queue" s="Farmer Mode"/><Actions/></div></Shell>}
function Head({t,s}){return <div className="head"><b>{t}</b><span>{s}</span></div>}
function Actions(){return <div className="actionsList">{[["01","Irrigation check","Moisture is within the demo target band. Recheck after forecast update."],["02","Disease scouting","Humidity trend warrants routine leaf inspection."],["03","Weather watch","Rain probability is moderate over the next 24h."]].map(x=><div className="action" key={x[0]}><b>{x[0]}</b><div><strong>{x[1]}</strong><p>{x[2]}</p></div><ArrowRight/></div>)}</div>}
function Doctor(){const[sym,setSym]=useState(""),[file,setFile]=useState(null),[loading,setLoading]=useState(false),[result,setResult]=useState(false);const run=()=>{setLoading(true);setResult(false);setTimeout(()=>{setLoading(false);setResult(true)},1200)};return <Shell ey="AI ASSISTED DIAGNOSIS" title="AI Crop Doctor" desc="A real inference workspace: symptom text + crop image + environmental context. This demo does not fabricate model accuracy."><div className="doctor"><div className="panel form"><label>Observed symptom</label><textarea value={sym} onChange={e=>setSym(e.target.value)} placeholder="Example: lower leaves are turning yellow after several humid days..."/><label>Crop image</label><label className="upload"><UploadCloud/><b>{file?file.name:"Upload crop image"}</b><small>JPG / PNG · local preview input</small><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="primary full" disabled={loading} onClick={run}>{loading?"Analyzing…":"Analyze crop"} <BrainCircuit/></button><small className="note">Production: connect this button to a verified ML/API endpoint through a backend.</small></div><div className="panel result">{loading?<div className="loader"><span/><b>Analyzing signals</b><small>Combining symptom, crop and environmental inputs</small></div>:!result?<div className="empty"><BrainCircuit/><h3>AI analysis workspace</h3><p>Describe a symptom or upload an image to begin.</p></div>:<div><div className="resultLine"><span>DEMO RESULT</span><small>Confidence: not estimated</small></div><h2>Possible nutrient or moisture stress</h2><p>This is an illustrative UI result. A real model must return a validated diagnosis and calibrated confidence.</p><div className="reason"><b>Why this recommendation?</b><p>Symptom + soil moisture + recent humidity would be contributing factors in a real decision engine.</p></div><div className="reason"><b>Recommended action</b><p>Inspect several plants, verify soil conditions and consult a locally validated crop-disease reference before treatment.</p></div></div>}</div></div></Shell>}
function Irrigation(){return <Shell ey="DECISION ENGINE" title="Smart Irrigation" desc="Transparent rules convert soil and forecast signals into an irrigation decision."><div className="decision"><div className="decisionDark"><span>DEMO DECISION</span><h2>Monitor — irrigation not triggered</h2><p>Moisture is inside the illustrative target band and forecast rain is non-zero.</p><div className="decisionStats">{[["48.2%","Soil moisture"],["32%","Rain probability"],["Moderate","Crop demand"],["—","Water estimate"]].map(x=><div key={x[1]}><small>{x[1]}</small><b>{x[0]}</b></div>)}</div></div><div className="panel"><b>Decision logic</b><ol><li>Compare moisture with crop-specific target.</li><li>Check forecast rain and heat.</li><li>Estimate crop water requirement.</li><li>Trigger only when configured evidence threshold is crossed.</li></ol></div></div></Shell>}
function Risk(){return <Shell ey="UNCERTAINTY-AWARE FORECAST" title="15-Day Agricultural Risk" desc="Risk is a changing signal, not a certainty. Demonstration values only."><div className="panel"><ResponsiveContainer width="100%" height={330}><LineChart data={risks}><CartesianGrid vertical={false} opacity=".2"/><XAxis dataKey="x"/><YAxis domain={[0,100]}/><Tooltip/><Line dataKey="heat" stroke="#e36d43" strokeWidth={3}/><Line dataKey="water" stroke="#4b82df" strokeWidth={3}/><Line dataKey="rain" stroke="var(--green)" strokeWidth={3}/><Line dataKey="disease" stroke="#965db3" strokeWidth={3}/></LineChart></ResponsiveContainer></div><div className="riskGrid">{[["Heat stress",24],["Water stress",32],["Excess rainfall",18],["Disease risk",28]].map(x=><div className="risk" key={x[0]}><span>{x[0]}</span><b>{x[1]}/100</b><small>Illustrative · model input required</small></div>)}</div></Shell>}
function Weather(){return <Shell ey="WEATHER INTELLIGENCE" title="72-Hour Weather" desc="Weather becomes an agricultural signal for irrigation, disease scouting and heat monitoring."><div className="weatherTop">{[["28–32°C","Temperature",Thermometer],["32%","Rain probability",CloudRain],["12 km/h","Wind",Wind]].map(x=>{const I=x[2];return <div key={x[1]}><I/><b>{x[0]}</b><small>{x[1]}</small></div>})}</div><div className="forecast">{["Now","+12h","+24h","+48h","+72h"].map((x,i)=><div key={x}><small>{x}</small><CloudRain/><b>{[28,30,31,29,27][i]}°C</b><span>{[18,24,32,47,35][i]}% rain</span></div>)}</div><div className="panel"><Head t="Weather → farm actions" s="Demo logic"/><Actions/></div></Shell>}
function Crops(){const crops=[["Rice",84,"Rainfall · moisture · season"],["Tomato",76,"pH · temperature · drainage"],["Maize",71,"N · temperature · rainfall"],["Chili",68,"Warm conditions · pH · moisture"]];return <Shell ey="CROP RECOMMENDATION ENGINE" title="Which crop fits this field?" desc="Suitability is a configurable agronomic score. Demo scores are not field-validated predictions."><div className="inputs">{["pH 6.4","N 72","P 38","K 64","Rain 1120mm"].map(x=><span key={x}>{x}</span>)}<button className="primary">Recalculate</button></div><div className="cropList">{crops.map(x=><div className="crop" key={x[0]}><span className="ficon"><Sprout/></span><div><b>{x[0]}</b><small>{x[2]}</small></div><div className="scoreBar"><i style={{width:x[1]+"%"}}/></div><strong>{x[1]}</strong><ArrowRight/></div>)}</div><div className="noteBox"><b>Score methodology</b><span>Weighted compatibility of pH, N/P/K, temperature, humidity, rainfall, location and season. Weights require calibration against a validated agronomic dataset.</span></div></Shell>}
function Soil(){return <Shell ey="SOIL INTELLIGENCE" title="Know the soil before choosing the action." desc="Measurements are compared with crop-specific target bands."><div className="soilGrid">{[["pH","6.4","5.8–7.0"],["Nitrogen","72 mg/kg","50–90"],["Phosphorus","38 mg/kg","25–50"],["Potassium","64 mg/kg","45–80"],["Moisture","48.2%","40–60%"],["Soil temp","27.1°C","22–30°C"]].map(x=><div className="soil" key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><span>Ideal {x[2]}</span><em>GOOD</em></div>)}</div></Shell>}
function FarmMap(){return <Shell ey="SPATIAL INTELLIGENCE" title="Farm zones" desc="GIS-ready zone visualization. No satellite imagery is claimed in this demo."><div className="map"><div className="mapCenter"><Satellite/><b>GIS layer ready</b><small>Connect real coordinates, sensors or remote sensing to activate.</small></div>{[["A1","healthy",22,27],["A2","monitor",58,38],["B1","healthy",32,63],["B2","dry",70,67]].map(x=><div className={"pin "+x[1]} style={{left:x[2]+"%",top:x[3]+"%"}} key={x[0]}>{x[0]}</div>)}</div></Shell>}
function Analytics(){return <Shell ey="ANALYTICS" title="From raw signals to measurable change." desc="Historical analytics become meaningful when connected to real sensor and experiment data."><div className="two"><div className="panel"><Head t="Moisture history" s="Simulation"/><ResponsiveContainer width="100%" height={290}><AreaChart data={moisture}><XAxis dataKey="x"/><YAxis/><Tooltip/><Area dataKey="m" type="monotone" stroke="var(--green)" fill="none" strokeWidth={3}/></AreaChart></ResponsiveContainer></div><div className="panel"><Head t="Validation metrics" s="No fabricated results"/><div className="big">48.2%<small>Current moisture</small></div><div className="big">—<small>Verified yield change</small></div><div className="big">—<small>Measured water saving</small></div></div></div></Shell>}
function Impact(){const[size,setSize]=useState(1);return <Shell ey="IMPACT CALCULATOR" title="Measure the impact — don't invent it." desc="This demo calculates only an illustrative baseline. Verified savings require measured control-vs-smart results."><div className="impact"><label>Farm size (ha)<input type="number" min=".1" step=".1" value={size} onChange={e=>setSize(+e.target.value||1)}/></label><label>Crop<select><option>Rice</option><option>Maize</option><option>Vegetable</option></select></label><label>Method<select><option>Conventional</option><option>Other</option></select></label><div className="impactOut"><small>Illustrative baseline</small><b>{(size*4200).toLocaleString()} L</b><span>Formula: area × 4,200 L/ha. Replace with locally validated crop-stage data.</span></div></div></Shell>}
function Method(){return <Shell ey="SCIENTIFIC METHOD" title="A decision-support pipeline, not just a dashboard." desc="Evidence → analysis → action → measurement."><div className="pipeline">{["Data Collection","Cleaning","Processing","AI / ML","Prediction & Risk","Decision Engine","Recommendation","Farm Action","Impact Measurement"].map((x,i)=><div key={x}><small>{String(i+1).padStart(2,"0")}</small><b>{x}</b>{i<8&&<ArrowRight/>}</div>)}</div><div className="two method"><div className="panel"><b>AI / ML transparency</b><ul><li>Model: not selected in demo</li><li>Inputs: sensor, weather, soil, crop, location</li><li>Training source: must be documented</li><li>Validation: held-out / field data</li><li>Confidence: calibrated before display</li><li>Limitations: visible to users</li></ul></div><div className="panel"><b>Data architecture</b><ul><li>Weather API</li><li>Soil / IoT sensor stream</li><li>Validated crop-disease dataset</li><li>PostgreSQL / Supabase</li><li>Python ML inference service</li><li>GIS / remote sensing only when actually connected</li></ul></div></div></Shell>}
createRoot(document.getElementById("root")).render(<App/>);
